CREATE TABLE IF NOT EXISTS user_daily_state (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  date DATE NOT NULL,
  free_draws_used INT UNSIGNED NOT NULL DEFAULT 0,
  total_draws INT UNSIGNED NOT NULL DEFAULT 0,
  consecutive_losses INT UNSIGNED NOT NULL DEFAULT 0,
  ad_task_done TINYINT(1) NOT NULL DEFAULT 0,
  invite_task_done TINYINT(1) NOT NULL DEFAULT 0,
  ad_draws_earned INT UNSIGNED NOT NULL DEFAULT 0,
  invite_draws_earned INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_date (user_id, date),
  CONSTRAINT fk_daily_user FOREIGN KEY (user_id) REFERENCES users(id)
);
